title: Superintendent Prototype
baseurl: "/naviance-proto/" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - node_modules